version: "3.9"
services:
  db:
    container_name: db-snsusm
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: snsusm_db
      MYSQL_USER: snsusm
      MYSQL_PASSWORD: 12346
    networks:
      - net-snsusm
  web:
    container_name: snsusm-web
    depends_on:
      - db
    ports:
      - "8085:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-snsusm
networks:
  net-snsusm:
    
